DNA_string = 'CCCACTTTTGGCCACACACTCTAATCATACTCCTGTTCTCAAAAAGGTAACCTTTCGCATAGCCTTAGCGTCAGGTGGCCAAAAACGGGCTGAAATCAAGCAATCAAATACACGGACAGTTTCGCACCTTCCTGACGCCTATTATTTCGAAAGGCAGTGATATTTTGCTCGGTCTCGACTGGCGTATTTCACTGTAAAGGATCAGAGCAATGGCGTTTATAGAGCGCCTGAAGGAATCTTATTAGGGACCTGGATGAGACCCTTTTAGAGAGCATCGCCTGGACGGTTGATTAGAGAGTATCCGCGTGAGTAGTGATTGTTGTTCTCAATGACCGATCTGACGGGGAAGGAATGGGCAGAATAGGAGTTGTCTGTTGTACGCTTTGTAAACATCTGGGTTCTGCAGGACGTTTGTTCACAGGTATTCGCGCCATGACAGCTAGGAAGTCGCGGTTATTCAACGCTGCTAAGAGTGTTGAACGCTTAATGAGGGTGTAAAAAGCCGGCGAGTACTTTTGCCCAAACAAATGAGAGGGTCCTCCCCAACCGCCCATCCAGTCTTCACGTCTGGCTCCCCGTATGGACTTCAGTCTCAACCCACTCTTTGCACACCCCCTAATCGCGAATTAAACAGACGACCGTGCGGTAAAGCTGGGTTTGTAACTAGGTGATGTGCTTCAGCTGTATAGGGTGATGGGATAGCAGCGACGCGGTGCTCGGGCGTGTACTCCGATTCATAGGACGTTCCGATCGGGGATTGCGGGTCAGGGACAACATCAATGCCAAAGTCGAAGAACACGAGTGTTACGCACACTTCAAATCAGTTCGGGATATGAATCCATTTATGAGTCTTCGGCCTACCTAAGGCACCCGTGCTACCAGCTTATGTCAAATCCTTTACGTAAACCTCCTACTAAGTCAGCACGTTCCCTCGACCGTTGACGTGATACATGCCGCCTTCAGCTTCTTCTATTGAGAGTCG'

result = ''
for nuc in DNA_string:
    
    if(nuc == 'A'):
        result = result + 'T'
    if(nuc == 'T'):
        result = result + 'A'
    if(nuc == 'C'):
        result = result + 'G'
    if(nuc == 'G'):
        result = result + 'C'

result = result[::-1]

print(result)